name: Workflow B

on:
  workflow_run:
    workflows:
      - "Workflow A"
    types:
      - completed

jobs:
  echo:
    name: Echo 2!
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world 2